# Generated by Django 4.0.1 on 2022-01-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='detail',
            field=models.TextField(blank=True, default='Скоро напишем новое описание', max_length=2000, null=True, verbose_name='Подробное описание'),
        ),
    ]
